Product tax
sQcrm/sqcrm-node-api pull request #48
Opened 2016-11-28 15:44 UTC by vivekshekar

@abhikchakraborty 

Product tax value enhancement.

2016-12-04 16:07 UTC, sQcrm commented on controllers/products.js
> +							});
@vivekshekar 
- Product has only `tax_value` and there is no other tax associated.
- So check only for `tax_value`
- Product does not have customized product number so we do not need that formatting part
- May be rename the function as `setProductTaxValues`

2016-12-04 16:08 UTC, sQcrm commented on controllers/products.js
> +							app.models.lineitems
Product does  not have line items so we may not need this function at all

2016-12-04 16:09 UTC, sQcrm requested changes
@vivekshekar added some changes needed to be done.

2016-12-08 06:32 UTC, vivekshekar commented
@abhikchakraborty Changes are done. 
Please check

2016-12-08 06:33 UTC, vivekshekar commented on controllers/products.js
> +							});
@abhikchakraborty updated

2016-12-08 06:33 UTC, vivekshekar commented on controllers/products.js
> +							app.models.lineitems
@abhikchakraborty updated

2016-12-10 19:49 UTC, abhikchakraborty commented on controllers/products.js
> +				//productPrefix = results.getProductPrifix;
remove this line.

2016-12-10 19:49 UTC, abhikchakraborty commented on controllers/products.js
>  							});
remove the above commented lines.

2016-12-10 19:51 UTC, abhikchakraborty reviewed
@vivekshekar tested the changes and looks good. There is a small change request before it could be merged.

2016-12-14 10:11 UTC, vivekshekar commented
@abhikchakraborty removed the commented lines.

2017-06-09 09:53 UTC, merged