Purchase Order
sQcrm/sqcrm-node-api pull request #49
Opened 2016-12-08 06:42 UTC by vivekshekar

@abhikchakraborty 

I have created purchase order api, but I cannot test this. As I cannot create purchase order on my local. I have created an issue with respect this on sqcrm issue,

https://github.com/sQcrm/sqcrm/issues/244

Please check the same and let me know.

2016-12-10 20:17 UTC, abhikchakraborty requested changes
@vivekshekar I had reviewed the task and left some comment. Please check.

2016-12-10 20:17 UTC, abhikchakraborty commented on controllers/purchaseorder.js
> +
`purchseorderPrefix` there is a typo and its used later as `purchaseorderPrefix` line:163

JS hint shows the errors as 
```
163 |                                if (purchaseorderPrefix && purchaseorderPrefix.settingData && k === 'po_number') {
                                             ^ 'purchaseorderPrefix' is not defined.
    163 |                                if (purchaseorderPrefix && purchaseorderPrefix.settingData && k === 'po_number') {
                                                                    ^ 'purchaseorderPrefix' is not defined.
    164 |                                    v= purchaseorderPrefix.settingData+''+v;
                                                ^ 'purchaseorderPrefix' is not defined.

```

2016-12-10 20:17 UTC, abhikchakraborty commented on controllers/purchaseorder.js
> +			crmPrivileges.userWhereCondition(req, 16, 'PurchaseOrder', 'purchase_order_custom_fld', true, function(err, whereCond) {
The 2nd param in the above function is the table name https://github.com/sQcrm/sqcrm-node-api/blob/pruchase_order/utils/crm_privileges.js#L285 
You are sending the module name, the table name is `purchase_order`

2016-12-10 20:17 UTC, abhikchakraborty commented on controllers/purchaseorder.js
> +							.find({recordid:purchase_order.id,moduleId:16})
`urchase_order.id` is undefined, and the loop is going as 
```
async.forEachOf(results.getRecords, function(purchaseorder, key, eachCallBack) {
```
So it should be as

```
.find({recordid:purchaseorder.id,moduleId:16})
```
Also all the variables, functions etc should be `camelCase` not `snake case`

2016-12-14 10:06 UTC, vivekshekar commented on controllers/purchaseorder.js
> +
@abhikchakraborty fixed the issues

2017-06-09 09:56 UTC, merged